version: "3.9"

services:
  flask_app:
    image: flask_web_app
    networks:
        - main_network
    ports:
        - "5000:5000"
  
  pg_admin:
    image: dpage/pgadmin4
    networks:
        - main_network
    ports:
        - "80:80"
    environment:
        - PGADMIN_DEFAULT_EMAIL=jakismail@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=zako123
  db:
    image: postgres
    networks:
        - main_network
    ports:
            - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=zako123

networks:
  main_network:

  